### ISSUE TITLE
💬 [Question] How to use this wonderful Library in our Project?

### ISSUE THREAD

**Issue by Tirokk** [ionut-botizan/vscode-cypher-ql#4]
I installed the VS Code extension. The syntax highlighting there works than. Wonderful!!!

But when I write the tag `cql` in front of a string with a cypher statement our backend complains that it doesn’t know what `cql` is:

```
        cql `
        MATCH (post:Post {id: $postId}), (comment:Comment {id: $commentId}), (author:User {id: $userId})
        MERGE (post)<-[:COMMENTS]-(comment)<-[:WROTE]-(author)
        RETURN comment, author`
```

Error Message:
```
ReferenceError: cql is not defined
```

What I can do to get this working, since you have no `npm` or `yarn` install?

**Comment by ionut-botizan** [comment]
Hello and sorry for the late reply!

Tagged templates in Javascript are actually function calls and something like
```js
const query = cql`MATCH (x) RETURN x`
```
is equivalent to 
```js
const query = cql(['MATCH (x) RETURN x'])
```
which means that, in order to use that syntax, you have to implement the `cql` function yourself or use some library that provides helpers/wrappers that work with Cypher queries.

---

### However... 🙂
...luckily for you, I have just released an update to the extension (v0.1.0) which adds a couple new ways to *tag* a string as a Cypher query and trigger the syntax highlight **without** the need for any custom function or 3rd party library: 
```js
// as a comment in Javascript, using either `cql` or `cypher` as a keyword
const query = /* cql */`
    MATCH (x) RETURN x
`
const query = /* cypher */`
    MATCH (x) RETURN x
`
//========================

// as a comment in Cypher itself, using either `cql` or `cypher` as a keyword
const query = `// cql
    MATCH (x) RETURN x
`

const query = `// cypher
    MATCH (x) RETURN x
`
```

Best Regards,
Ionuț
